### ISSUE TITLE
is sort sorting by balance or names? seems like names

### ISSUE THREAD

**Issue by officialnico** [officialnico/balancerV2_Model#16]
https://github.com/officialnico/balancerV2_Model/blob/5d1d30ab343125d06b8b700ab8a1ced6122a6afe/model/pools/BasePool.py#L12

**Comment by tommyliu9** [comment]
you can specify what to sort by specifying the param with a lambda: 
![image](https://user-images.githubusercontent.com/25253929/118272370-5c71c580-b477-11eb-935a-336bf5b25e32.png)
